### ISSUE TITLE
Duel Ranking negative values sorting issue

### ISSUE THREAD

**Issue by andrei9619** [tasks-delivery/MuOnline#376]
**Precondition:**
Server Exile 1000 exists in the system
6 users with negative Scores attend Duel event

**Steps to Reproduce:**
1. Go to womu.by
2. Click 'Ranking' link in the header
3. Click on server from precondtion
4. Click 'Duel ranking' link

**Actual result:** Users with negative values sorting alphabetically from the end 
**Expected result:** Users with negative values sorting by score from highest to lowest

![Screen Shot 2021-11-28 at 1 50 59 PM](https://user-images.githubusercontent.com/61422820/143781755-3cde22fc-2c76-4b15-a534-060d1940cebf.png)

**Comment by ordeh** [comment]
I fixed this and pushed into production womu.by. @andrei9619 Could you re-check this and create test-case on this bug.

**Comment by andrei9619** [comment]
@ordeh 
I'm not able to test it now, they're only 2 attendant at the moment.
Working on the test case

**Comment by andrei9619** [comment]
@ordeh 
Test case located at:
https://app.qase.io/case/WOMU/edit/112

**Comment by andrei9619** [comment]
@ordeh 
The issue is still there
![Screen Shot 2021-12-03 at 8 52 36 AM](https://user-images.githubusercontent.com/61422820/144613763-e7f773c5-63ac-4020-8bc4-cd32558570d0.png)

**Comment by ordeh** [comment]
@andrei9619 

Will fix in https://github.com/tasks-delivery/MuOnline/issues/368 tiket
